### ISSUE TITLE
Toy test failed

### ISSUE THREAD

**Issue by Carlos-Chau** [id-bioinfo/TIPars#1]
Toy test failed to run 

Unzipping [test/sars2_1k/taxa.zip](https://github.com/id-bioinfo/TIPars/blob/master/test/sars2_1k/taxa.zip) gave 'taxa_part1_generated.fasta', **not** 'taxa.fasta'

Modified test run code ran to completion, but did not produce a new 'tipars.tree' file
```
./tipars -t test/sars2_1k/ref.tree \
         -s test/sars2_1k/taxa_part1_generated.fasta \
         -a test/sars2_1k/ancseq.fasta \
         -q test/sars2_1k/query.fasta \
         -o test/sars2_1k/tipars.tree \
         > output.txt
```

[output.txt](https://github.com/id-bioinfo/TIPars/files/8462826/output.txt)

**Comment by ytye2010** [comment]
Thanks for trying TIPars. Due to GISAID's data sharing policy, only Accession Numbers are provided for the sequences downloaded from GISAID in this sars2-1k dataset. I sent you the complete dataset directly by email. If you just want to have a try of TIPars, regardness of SARS2, please refer to our benchmark datasets of H3N2 which has been set to toy testing example now.

**Comment by ytye2010** [comment]
Thanks for trying TIPars. Due to GISAID's data sharing policy, only Accession Numbers are provided for the sequences downloaded from GISAID in this sars2-1k dataset. I sent you the complete dataset directly by email. If you just want to have a try of TIPars, regardness of SARS2, please refer to our benchmark datasets of H3N2 which has been set to toy testing example now.

**Comment by ytye2010** [comment]
Thanks for trying TIPars. Due to GISAID's data sharing policy, only Accession Numbers are provided for the sequences downloaded from GISAID in this sars2-1k dataset. I sent you the complete dataset directly by email. If you just want to have a try of TIPars, regardness of SARS2, please refer to our benchmark datasets of H3N2 which has been set to toy testing example now.

**Comment by Carlos-Chau** [comment]
Alright, thanks for reply

**Comment by ytye2010** [comment]
Thanks for trying TIPars. Due to GISAID's data sharing policy [6](https://github.com/id-bioinfo/TIPars#user-content-fn-6-c66d10f6010e536a30c3d1f300103923), only Accession Numbers are provided for the sequences downloaded from GISAID. If you just want to have a try on TIPars, regardness of SARS2, we recommend you to test on our H3N2 completed benchmark dataset at the folder Benchmark datasets/H3N2.

**Comment by ytye2010** [comment]
Thanks for trying TIPars. Due to GISAID's data sharing policy, only Accession Numbers are provided for the sequences downloaded from GISAID. If you just want to have a try on TIPars, regardness of SARS2, we recommend you to test on the NDV completed benchmark dataset at the folder Benchmark datasets/NDV.
